channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - matplotlib
  - networkx
  - numpy
  - pandas
  - pip
  - prettytable
  - pydtmc
  - python=3.8
  - python-dateutil
  - pytorch::pytorch=1.10.*
  - pytorch::cpuonly
  - pyyaml
  - requests
  - ruamel.yaml
  - scikit-learn
  - scipy
  - seaborn
  - shap
  - tensorflow=2.*
  - pytorch::torchvision
  - pip:
    - hmmviz==0.0.7
