name: &save_config
  save_path: ['./data', 'pkl', 'feature_engineering']
  save_name: null
  verbose: True
  refresh: False

nocturia:
  time_range: ['22:00', '06:00']

bathroom_night:
  save: *save_config

bathroom_daytime:
  save: *save_config

bathroom_urgent:
  recall_value: 2
  save: *save_config

body_temperature:
  save: *save_config

raw_activity:
  save: *save_config

activity:
  features: ['raw_activity', 'bathroom_night', 'bathroom_daytime', 'body_temperature']
  save: *save_config
