name:
  - &architecture
      input_dim: 336
      latent_dim: 200
      out_dim: 100
  - &train
      epochs: 50
      verbose: True
      retrain: False
  - &loader
      batch_size: 512
      augmentation: False
  - &optimiser
      lr: 0.01
      weight_decay: 0.01
  - &early_stop
      enable: True
      patience: 200
      verbose: False
      delta: 0
      path: './ckpt/feature_extractors'
      save_model: True
  - &test
      save: True
      save_path: './data/extracted_features'


simclr:
  model:
    base_model: 'basic'
    << : *architecture
  optimiser:
    <<: *optimiser
  train:
    <<: *train
  loader:
    <<: *loader
    augmentation: True
  test: *test
  early_stop:
    <<: *early_stop
  loss:
    temperature: 0.5
    use_cosine_similarity: True



partial_order:
  model:
    base_model: 'conv'
    << : *architecture
  optimiser:
    <<: *optimiser
  train:
    <<: *train
  loader:
    augmented_day: 3
    normalise: True
  test:
    <<: *test
  early_stop:
    <<: *early_stop
  loss:
    delta: 0.5
    use_cosine_similarity: True


autoencoder:
  model:
    base_model: 'conv'
    << : *architecture
  optimiser:
    <<: *optimiser
  train:
    <<: *train
  loader:
    <<: *loader
  test:
    <<: *test
  early_stop:
    <<: *early_stop
  loss:
    func: 'bce'