name: &save_config
  save_path: './data/pkl/feature_engineering'
  save_name: null
  verbose: True
  refresh: False

nocturia:
  time_range: ['22:00', '06:00']

bathroom_night:
  save: *save_config

bathroom_daytime:
  save: *save_config

body_temperature:
  save: *save_config
