name: &save_config
  save_path: './data/pkl/weekly_data'
  save_name: null
  verbose: True
  refresh: False

physiological:
  type: [ 'raw_body_weight', 'raw_skin_temperature',
          'raw_body_temperature', 'raw_body_muscle_mass',
          'raw_heart_rate', 'raw_oxygen_saturation',
          'raw_total_body_fat', 'raw_body_mass_index',
          'raw_blood_pressure', 'raw_total_body_water',
          'raw_total_bone_mass' ]
  columns: [ 'id', 'time', 'location', 'value' ]
  sensors: [ 'body_mass_index',
             'body_muscle_mass',
             'body_temperature',
             'body_weight',
             'diastolic',
             'heart_rate',
             'oxygen_saturation',
             'skin_temperature',
             'systolic',
             'total_body_fat',
             'total_body_water',
             'total_bone_mass' ]
  add_tihm: True
  save: *save_config

activity:
  type: [ 'raw_door_sensor', 'raw_appliance_use', 'raw_activity_pir' ]
  columns: [ 'id', 'time', 'location', 'value' ]
  sensors: [ 'back door', 'bathroom1', 'bedroom1', 'dining room',
             'fridge door', 'front door', 'hallway', 'kettle', 'kitchen',
             'living room', 'lounge', 'microwave', 'study', 'toaster' ]
  add_tihm: True
  save: *save_config

environmental:
  type: ['raw_ambient_temperature', 'raw_light']
  columns: ['id', 'time', 'location', 'value']
  sensors: [ 'back door', 'bathroom1', 'bedroom1', 'fridge door', 'front door',
             'hallway', 'kitchen', 'lounge', 'study', 'conservatory',
             'dining room', 'main door', 'cellar', 'living room', 'WC1',
             'corridor1', 'secondary', 'office', 'garage' ]
  save: *save_config

individuals:
  text: [ 'homes', 'raw_sleep_mat', 'raw_behavioural',
          'procedure', 'observation_notes', 'encounter',
          'issue' ]
  measure: ['raw_sleep_event', 'raw_wearable_walking']
  save: *save_config

labelled_data:
  save:
    save_path: './data/pkl/raw_data'
    save_name: null
    verbose: True
    refresh: False

unlabelled_data:
  save: *save_config

activity_nice_locations:
  hallway: 'Hallway'
  kitchen: 'Kitchen'
  lounge: 'Lounge'
  bathroom1: 'Bathroom'
  bedroom1: 'Bedroom'
  kettle: 'Kettle'
  toaster: 'Toaster'
  fridge door: 'Fridge Door'
  back door: 'Back Door'
  front door: 'Front Door'
  microwave: 'Microwave'
  study: 'Study'
  dining room: 'Dining Room'
  living room: 'Living Room'
  iron: 'Iron'
  corridor1: 'Corridor'
  WC1: 'WC'
  main door: 'Main Door'
  utility: 'Utility'
  office: 'Office'
  multi: 'Multi'
  conservatory: 'Conservatory'
  garage: 'Garage'
  secondary: 'Secondary'
  cellar: 'Cellar'
